### ISSUE TITLE
Installation steps?

### ISSUE THREAD

**Issue by brudarko** [nozarc/dacha#1]
Your project will help me so much. Waiting for some instructions .

**Comment by brudarko** [comment]
Also, what's the default password?

**Comment by nozarc** [comment]
sorry, this app is still under development, but I think it's already stable, so you can try this out. 
this app connected directly to your Mikrotik and still database-less, you can log in with your Mikrotik admin username and password

**Comment by brudarko** [comment]
Thank you, got it working. Gonna make some changes, but it's a beginning.

**Comment by nozarc** [comment]
ahahah, you're welcome dude.
